### ISSUE TITLE
Unable to compile do_oracle.c with Ruby 2.0.0-p0

### ISSUE THREAD

**Issue by DavidJLee** [datamapper/do#52]
Able to compile properly when using Ruby 1.9.3. Tested with patch levels 327 and 392. Unable to compile using Ruby 2.0.0

compiling do_oracle.c
do_oracle.c: In function ‘data_objects_debug’:
do_oracle.c:123: warning: ISO C90 forbids mixed declarations and code
do_oracle.c:125: warning: implicit conversion shortens 64-bit value into a 32-bit value
do_oracle.c: In function ‘cDO_OracleCommand_execute_internal’:
do_oracle.c:393: warning: ISO C90 forbids mixed declarations and code
do_oracle.c: In function ‘cDO_OracleCommand_execute_try’:
do_oracle.c:415: error: expected ‘(’ before ‘!’ token
do_oracle.c:415: warning: statement with no effect
do_oracle.c:415: error: expected ‘;’ before ‘{’ token
do_oracle.c:412: warning: unused variable ‘insert_id_present’
do_oracle.c: In function ‘cDO_OracleConnection_initialize’:
do_oracle.c:464: warning: initialization discards qualifiers from pointer target type
do_oracle.c:464: warning: initialization discards qualifiers from pointer target type
do_oracle.c:508: warning: passing argument 2 of ‘get_uri_option’ discards qualifiers from pointer target type
do_oracle.c:519: warning: passing argument 2 of ‘get_uri_option’ discards qualifiers from pointer target type
do_oracle.c: In function ‘cDO_OracleCommand_execute_non_query’:
do_oracle.c:547: warning: ISO C90 forbids mixed declarations and code
do_oracle.c: In function ‘cDO_OracleReader_next’:
do_oracle.c:636: warning: ISO C90 forbids mixed declarations and code
make: **\* [do_oracle.o] Error 1
